### ISSUE TITLE
Missing few device models in notchDevices()

### ISSUE THREAD

**Issue by VenkateshMahi** [Vignesh-Thangamariappan/DeviceUtility#1]
https://github.com/Vignesh-Thangamariappan/DeviceUtility/blob/a1e6ca73bf98e20255c75d5ca826c42329f7d2cb/Sources/DeviceUtility/DeviceUtility.swift#L167

Kindly add iPhone13, iPhone13Pro and iPhone13Pro Max to the notchDevices list

**Comment by Vignesh-Thangamariappan** [comment]
The issue has been addressed in v0.1.2.
